rtx fix complete

diff --git a/run_onchange_install-packages.bash.tmpl b/run_onchange_install-packages.bash.tmpl
--- a/run_onchange_install-packages.bash.tmpl
+++ b/run_onchange_install-packages.bash.tmpl
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
 # A chezmoi script to install all the dependencies I need on a new machine
 
+
+
 if ! command -v brew &> /dev/null
 then
     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
@@ -62,20 +64,19 @@ if [ ! -d $RTX_BIN ]; then
     curl https://rtx.pub/install.sh | sh
 fi
 
-alias rtx=$RTX_BIN
-alias asdf="rtx"
+eval "$($RTX_BIN activate bash)"
 
 install_package() {
     package=$1
 
     # Add the package to asdf
-    asdf plugin add $package
+    rtx plugin add $package
 
     # Check if the package is already installed
-    if ! asdf list $package | grep -q "$(asdf latest $package)"; then
+    if ! rtx list $package | grep -q "$(rtx latest $package)"; then
         # If not, install the latest version of the package
-        asdf install $package latest
-        asdf global $package latest
+        rtx install $package@latest
+        rtx global $package@latest
     else
         # If it is, print a message saying that the package is already installed
         echo "$package is already installed"
@@ -92,6 +93,8 @@ done
 
 # pipx req
 install_apt_package python3-venv
+
+#TODO: pipx and pnpm fails to install
 
 sudo apt install htop
 sudo apt install ncdu
@@ -121,9 +124,9 @@ else
     echo "ctop is already installed"
 fi
 
-asdf plugin add lazydocker https://github.com/comdotlinux/asdf-lazydocker.git
-asdf install lazydocker latest
-asdf global lazydocker latest
+rtx plugin add lazydocker https://github.com/comdotlinux/asdf-lazydocker.git
+rtx install lazydocker@latest
+rtx global lazydocker@latest
 
 # tldr
 # https://tracker.debian.org/pkg/rust-tealdeer
